<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * String definitions of subplugin
 *
 * @package    gradebook
 * @subpackage progress
 * @copyright  2011 MoodleFN
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
 
//subreport summary class strings
$string['summary'] = 'summary';
$string['summarytitle'] = 'Summary subreport';
$string['summarytotalgradeitemheading'] = 'Grade item totals';
$string['summarytotalgradeitems'] = 'Total number of grade items';
$string['summarytotalcomplete'] = 'Total complete';
$string['summarytotalincomplete'] = 'Total incomplete';
$string['summarytotalhidden'] = 'Total hidden';
$string['summarytotallocked'] = 'Total locked';
$string['summarytotalungraded'] = 'Total ungraded';
$string['summarytotalnograde'] = 'Total no grade';
$string['summaryoverallheading'] = 'Overall grades';
$string['summaryoverallmoodle'] = 'Overall grade from Moodle';
$string['summaryoverallsubmitted'] = 'Overall grade based on submitted assignments';
$string['summaryoverallavailable'] = 'Overall grade based on available assignments';
$string['summarylastaccess'] = 'Last logged in';
$string['summaryoveralldummyuserlocked'] = 'Overall dummy user locked';
$string['summaryusageheading'] = 'Usage';
$string['summaryhourslogged'] = 'Approximate hours spent in course';
$string['summaryweeksleft'] = 'Weeks left';
$string['summarynotapplicable'] = 'Not applicable';
$string['summarydaysago'] = ' days ago';

//subreport summary settings strings
$string['settingsumname'] = 'Summary subreport settings';
$string['settingsumfulldescription'] = 'The summary subreport gives statistics derived from counting grade items filtered on the state of their completeness.  Overall grade stats and estimates of attendance are also provided.';
$string['settingsumenabled'] = 'Enable summary subreport';
$string['settingsumenableddescription'] = 'Check box to allow users to select the summary subreport/ uncheck to remove the summary report as an option.';
$string['settingsumenableddescription_help'] = 'Check box to allow users to select the summary subreport/ uncheck to remove the summary report as an option.';
$string['settingsumweight'] = 'Default weight';
$string['settingsumweightdescription'] = 'The default weight of the summary subreport as a numeric value.  Lower values place the summary subreport earlier in the sequence of selected subreports.  note that a value of -1 should disable the subreport.';
$string['settingsumweightdescription_help'] = 'The default weight of the summary subreport as a numeric value.  Lower values place the summary subreport earlier in the sequence of selected subreports.  note that a value of -1 should disable the subreport.';
$string['settingsumtotalactivities'] = 'Display total number of activities';
$string['settingsumtotalactivitiesdescription'] = 'Activities are represented by any grade items which are of the module type.';
$string['settingsumtotalactivitiesdescription_help'] = 'Activities are represented by any grade items which are of the module type.';
$string['settingsumtotalcomplete'] = 'Display total number of completed activities';
$string['settingsumtotalcompletedescription'] = 'Completion is determined by Moodle\'s completion tracking system.  See http://docs.moodle.org/22/en/Activity_completion for additional details.';
$string['settingsumtotalcompletedescription_help'] = 'Completion is determined by Moodle\'s completion tracking system.  See http://docs.moodle.org/22/en/Activity_completion for additional details.';
$string['settingsumtotalincoomplete'] = 'Display total number of incomplete activities';
$string['settingsumtotalincoompletedescription'] = 'Completion is determined by Moodle\'s completion tracking system.  See http://docs.moodle.org/22/en/Activity_completion for additional details.';
$string['settingsumtotalincoompletedescription_help'] = 'Completion is determined by Moodle\'s completion tracking system.  See http://docs.moodle.org/22/en/Activity_completion for additional details.';
$string['settingsumgradesubmitted'] = 'Display the user\'s grade as calculated by submitted assignments';
$string['settingsumgradesubmitteddescription'] = 'This value is generated by adding by cloning the user\'s grades to a dummy user and examining the dummy user\'s course grade in Moodle.  This value will usually be of equal value to the course grade generated by Moodle';
$string['settingsumgradesubmitteddescription_help'] = 'This value is generated by adding by cloning the user\'s grades to a dummy user and examining the dummy user\'s course grade in Moodle.  This value will usually be of equal value to the course grade generated by Moodle.';
$string['settingsumgradeavailable'] = 'Display the user\'s grade as calculated based on all available assignments';
$string['settingsumgradeavailabledescription'] = 'This value is generated by cloning the user\'s grades to a dummy user and assigning a grade of minimum value to the dummy user for each available but unattempted assignment.  This value will be different from Moodle\'s generated course grade if the user has not attempted all available activities.  Available assignments are those considered available by Moodle.  Considerations are based on whether or not the assignment is open and visible.  The grade value may be different than expected if the user has not recieved a grade in a closed activity (users should be given a minimum grade in closed assignments, by teachers, to enusure that this field generates useful information).';
$string['settingsumgradeavailabledescription_help'] = 'This value is generated by cloning the user\'s grades to a dummy user and assigning a grade of minimum value to the dummy user for each available but unattempted assignment.  This value will be different from Moodle\'s generated course grade if the user has not attempted all available activities.  Available assignments are those considered available by Moodle.  Considerations are based on whether or not the assignment is open and visible.  The grade value may be different than expected if the user has not recieved a grade in a closed activity (users should be given a minimum grade in closed assignments, by teachers, to enusure that this field generates useful information).';
$string['settingsumlastlogin'] = 'Display the user\'s last recorded course login';
$string['settingsumlastlogindescription'] = 'This value represents the user\'s last access to the course and not the context of that access.  What the user did during their last login is not tracked.';
$string['settingsumlastlogindescription_help'] = 'This value represents the user\'s last access to the course and not the context of that access.  What the user did during their last login is not tracked.';
$string['settingsumtotallogin'] = 'Display the user\'s total time spent logged into the course';
$string['settingsumtotallogindescription'] = 'This value is generated by collecting the user\'s access logs and tracking how many different hours theses accesses happened across.  Because logs are based on page requests and it is unknown how long a user might spend on an open page, this value is an approximation.';
$string['settingsumtotallogindescription_help'] = 'This value is generated by collecting the user\'s access logs and tracking how many different hours theses accesses happened across.  Because logs are based on page requests and it is unknown how long a user might spend on an open page, this value is an approximation.';
$string['settingsumweeksleft'] = 'Display the total weeks left that the user has in the course.';
$string['settingsumweeksleftdescription'] = 'The total weeks left is determined by the time remaining in the user\'s enrollment as tracked by Moodle.';
$string['settingsumweeksleftdescription_help'] = 'The total weeks left is determined by the time remaining in the user\'s enrollment as tracked by Moodle.';